config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  get "dashboard", to: "pages#dashboard" # route du dashboard
  get "events/:id/invite", to: "events#invite", as: :invite # page d'invitation
  get "events/:event_id/bars", to: "bars#index", as: :bars
  post "events/:event_id/bars", to: "bars#create_bars", as: :create_bars
  get "events/:id/barocentre", to: "events#barocentre", as: :barocentre  # page de la map avec barocentre
  get "events/:event_id/bars/map", to: "bars#map", as: :map # page de la map avec les bars
  get "events/:event_id/event_users/map", to: "event_users#map", as: :map_event_users # page de la map avec les event_users
  resources :events, only: [:new, :create, :show] do # route du new, show, create event
    get "/classment", to: "bars#classment", as: :classment # page du classement
    get :choose_bar
    get "/itineraire", to: "events#itineraire", as: :itineraire # page de l'itinéraire
    resources :votes, only: [:create]
    resources :event_users, only: [:new, :create, :index] # route du new, create, index event_user
  end
  resources :event_users, only: [:destroy]
end

app/models/event_user.rb
class EventUser < ApplicationRecord
  belongs_to :event
  belongs_to :user
  has_many :votes, dependent: :destroy
  validates :user_address, presence: true
  validates_uniqueness_of :user_id, scope: [:event_id]
  validates :transport, presence: true, inclusion: { in: %w[driving transit bicycling] }

  geocoded_by :user_address
  after_validation :geocode, unless: :lon_lat_changed?

  def transport_icon
    {
      'bicycling' => '<i class="fa-solid fa-person-biking"></i>',
      'transit' => '<i class="fa-solid fa-train-subway"></i>',
      'driving' => '<i class="fa-solid fa-car"></i>'
    }[transport].html_safe
  end

  private

  def lon_lat_changed?
    longitude_changed? && latitude_changed?
  end
end

app/controllers/event_users_controller.rb
require "json"
require "open-uri"

class EventUsersController < ApplicationController
  def index
    @event = Event.find(params[:event_id])
    @eventusers = @event.event_users
    @markers = @eventusers.geocoded.map do |eventuser|
      {
        lat: eventuser.latitude,
        lng: eventuser.longitude,
        user_name: eventuser.user.email,
        info_window_html: render_to_string(partial: "info_window", locals: {event_user: eventuser} ),
        marker_html: render_to_string(partial: "marker", locals: {event_user: eventuser})
      }
    end
  end

  def new
    @event_user = EventUser.new
    @event = Event.find(params[:event_id])
  end

  def create
    @event = Event.find(params[:event_id])
    @event_user = EventUser.new(event_user_params)
    @event_user.user = current_user
    @event_user.event = @event
    if @event_user.save!
      EventChannel.broadcast_to(@event, {event_user: render_to_string(partial: "event_user", locals: { element: @event_user })})
      redirect_to event_event_users_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
    @event.open!
  end

  def destroy
    @event_user = EventUser.find(params[:id])
    @event = @event_user.event
    @event_user.destroy
    redirect_to event_event_users_path(@event), status: :see_other
  end

  def map
    @event = Event.find(params[:event_id])
    @eventusers = @event.event_users
    @markers = @eventusers.geocoded.map do |eventuser|
      {
        lat: eventuser.latitude,
        lng: eventuser.longitude,
        user_name: eventuser.user.email,
        info_window_html: render_to_string(partial: "info_window", locals: {event_user: eventuser} ),
        marker_html: render_to_string(partial: "marker", locals: {event_user: eventuser} )
      }
    end
  end

  private

  def event_user_params
    params.require(:event_user).permit(:user_address, :transport, :latitude, :longitude)
  end
end

app/views/event_users/_event_user.html.erb
<div class="col-sm-3 col-lg-4 mb-2">
  <div class="d-flex flex-row justify-content-start align-items-center my-1" style="background: #FFC300; border-radius: 50px; width: 300px">
    <% if element.user.photo.attached? %>
      <%= image_tag element.user.photo, class: "dash-avatar me-3", style: "border: 4px solid white;" %>
    <% else %>
      <%= image_tag "https://as1.ftcdn.net/v2/jpg/03/53/11/00/1000_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg", class: "rounded-circle me-3", style: "width: 100px" %>
    <% end %>
    <p class="text-ellipsis--2 mt-3" style="font-size: 13px; width: 150px">
      <% if @event.user == element.user %>
        <i class="fa-solid fa-crown"></i>
      <% end %>
      <strong><%= element.user.username.capitalize %></strong> - <%= element.transport_icon %>
      <br>
      <%= element.user_address %>
    </p>
    <div data-event-subscription-target="trashcan" class="trashcan">
      <%# if element.user != current_user %>
        <div class="ms-2 d-flex justify-content-center align-items-end">
          <%= link_to event_user_path(element),
                      data: {
                        turbo_method: :delete,
                        turbo_confirm: "Voulez-vous retirer #{element.user.username.capitalize} de l'évènement #{@event.name.capitalize} ?"
                      } do %>
            <i class="fa-regular fa-trash-can me-3"></i>
          <% end %>
        </div>
      <%# end %>
    </div>
  </div>
</div>

app/views/event_users/_marker.html.erb
<% if event_user.user.photo.attached? %>
  <%= cl_image_tag event_user.user.photo.key, :width=>50, :height=>50, :radius=>"max", :crop=>"fill", class: "rounded-circle avatar-bordered" %>
<% else %>
  <%= image_tag "https://as1.ftcdn.net/v2/jpg/03/53/11/00/1000_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg", class: "rounded-circle", style: " width: 50px"%>
<% end %>

app/views/event_users/barocentre.html.erb
<div class="wraper">
  <div class="baro-map"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-barmarker-value="<%= @barycenter_marker.to_json%>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

  <%= link_to "Voir les bars", bars_path, class: "btn btn-ghost", style: "position: fixed; bottom: 30px; left: 120px" %>
</div>

app/views/event_users/index.html.erb
<div class="index wraper" data-controller="event-subscription sweatalert"
      data-event-subscription-event-id-value="<%= @event.id%>"
      data-event-subscription-current-user-id-value="<%= current_user.id%>">
  <div class="justify-content-center">
    <div class="col-sm-3 col-lg-12 ps-5 pe-5 pt-3 pb-2">
      <div class="text-center mt-2">
        <div class="d-flex justify-content-center" style="width: 100">
          <h1><%= @event.name.capitalize %></h1>
        </div>


        <div class="d-flex justify-content-center mb-3 btn-wrapper" >
        <% if current_user == @event.user %>
          <div class="btn btn-bar" data-action="click->sweatalert#fire">
            <div class="d-flex justify-content-center align-items-center" >
              <i class="animate__animated animate__wobble animate__infinite fa-solid fa-dice"></i>
            </div>
          </div>
            <%= link_to "lol", create_bars_path(@event), class: "d-none", data: { turbo_method: :post, sweatalert_target: "link"} %>
          <% end %>
          <div class="d-none" data-sweatalert-target="loader">
            <%= render "shared/loader" %>
          </div>
        </div>
      </div>
        <p class="text-center"><i class="fa-solid fa-crown"></i> <strong><%= @event.user.username %></strong></p>
        <div class="d-flex border-bottom border-secondary justify-content-between align-items-center mt-5 mb-3 pb-1">
          <p class="text-start" style="font-size: 16px; margin: 0px;">Participants</p>
          <span class="btn-minishare" data-controller="share"
                data-action="click->share#share"
                data-share-title-value="<%= @event.name %>"
                data-share-url-value="<%= new_event_event_user_url(@event) %>">
                <i class="fa-solid fa-share-from-square"></i>
          </span>
        </div>
      <div class="row d-flex justify-content-center pt-2 <%= "owner" if @event.user == current_user %>" data-event-subscription-target="users">
        <% @eventusers.each do |element| %>
          <%= render "event_users/event_user", element: element%>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-sm-3 col-lg-12 d-flex justify-content-center" data-sweatalert-target="map">
    <%= link_to map_event_users_path, class: "btn btn-ghost", style: "border: 1px solid black; border-radius: 20Px; position : fixed; bottom : 50px;" do %>
      CARTE <i class="fa-solid fa-map"></i>
    <% end %>
  </div>
</div>

app/views/event_users/map.html.erb
<div class="baro-map"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
<%= link_to event_event_users_path, class: "btn btn-ghost", style: "border: 1px solid black; border-radius: 20Px; position : fixed; bottom : 30px; left: 50%; transform: translateX(-50%);" do %>
  LISTE <i class="fa-solid fa-list"></i>
<% end %>

app/views/event_users/new.html.erb
<div class="container custom-container">
  <div class="pt-5">

    <div class="d-flex flex-column justify-content-center">

      <h1 class="text-center fw-bold" style="color: #001D3D"><%= @event.name.capitalize %></h1>

      <h5 class="text-center fw-light" style="color: #FFC300"><i class="fa-regular fa-calendar"></i> <%= I18n.l(@event.date).capitalize %></h5>
    </div>

    <br>
    <br>
    <br>

    <%= simple_form_for [@event, @event_user],
                        html: {
                          data: {
                            controller: "address-autocomplete",
                            address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]
                          }
                        } do |f| %>
      <%= f.input :user_address,
                  label: false,
                  placeholder: "68 avenue Parmentier",
                  input_html: {
                    class: 'd-none',
                    data: {
                      address_autocomplete_target: "address",
                    }
                  },
                  wrapper_html: {
                    data: {
                      address_autocomplete_target: 'wrapper'
                    }
                  } %>
<br>
      <%= f.input :latitude, as: :hidden, input_html: { data: { address_autocomplete_target: 'latitude' } } %>
      <%= f.input :longitude, as: :hidden, input_html: { data: { address_autocomplete_target: 'longitude' } } %>
      <%= f.input :transport, legend_tag: false, as: :radio_buttons,
            collection_wrapper_tag: 'div',
            collection_wrapper_class: 'category-wrapper',
            item_wrapper_class: 'category-item',
            input_html: {class: 'category-selector'},
            collection: ["driving", "transit", "bicycling"],
            label_method: ->(cat) {
              content_tag('span') { " "
              }
            } %>
      <br>
            <div class="d-flex justify-content-end">
              <%= f.submit "Je participe !", class: "btn btn-ghost me-3 mb-3"%>
            </div>
    <% end %>
  </div>
</div>
<%= render 'shared/footer' %>