config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  get "dashboard", to: "pages#dashboard" # route du dashboard
  get "events/:id/invite", to: "events#invite", as: :invite # page d'invitation
  get "events/:event_id/bars", to: "bars#index", as: :bars
  post "events/:event_id/bars", to: "bars#create_bars", as: :create_bars
  get "events/:id/barocentre", to: "events#barocentre", as: :barocentre  # page de la map avec barocentre
  get "events/:event_id/bars/map", to: "bars#map", as: :map # page de la map avec les bars
  get "events/:event_id/event_users/map", to: "event_users#map", as: :map_event_users # page de la map avec les event_users
  resources :events, only: [:new, :create, :show] do # route du new, show, create event
    get "/classment", to: "bars#classment", as: :classment # page du classement
    get :choose_bar
    get "/itineraire", to: "events#itineraire", as: :itineraire # page de l'itinéraire
    resources :votes, only: [:create]
    resources :event_users, only: [:new, :create, :index] # route du new, create, index event_user
  end
  resources :event_users, only: [:destroy]
end

app/models/bar.rb
class Bar < ApplicationRecord
  has_many :votes, dependent: :destroy
  validates :name, uniqueness: { scope: :event_id }
  validates :address, presence: true
  belongs_to :event

  def most_voted?
    event.most_voted_bars.include?(self)
  end
end

app/controllers/bars_controller.rb
require "uri"
require "net/http"

class BarsController < ApplicationController
  def index
    @event = Event.find(params[:event_id])
    @event.vote!
    @bars = Bar.where(event_id: params[:event_id])
  end

  def map
    @event = Event.find(params[:event_id])
    @bars = Bar.where(event_id: params[:event_id])
    @markers = @bars.map do |bar|
      {
        lat: bar.latitude,
        lng: bar.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {bar: bar}),
          marker_html: render_to_string(partial: "marker", locals: {bar: bar})
      }
    end
    @barycenter_marker = [{
      lat: @event.barycenter_lat,
      lng: @event.barycenter_lng,
      marker_html: render_to_string(partial: "marker")
    }]
  end

  def create
    @event = Event.find(params[:event_id])
    @bar = Bar.new(bar_params)
    @bar.event = @event
    if @bar.save
      redirect_to event_bars_path(@event)
    else
      render :index
    end
  end

  def create_bars
    @event = Event.find(params[:event_id])
    second_barycenter
    get_bars_from_google(@event)

    EventChannel.broadcast_to(@event, { url: bars_path(@event), current_user_id: current_user.id })

    redirect_to barocentre_path(@event)
  end

  def new
    @event = Event.find(params[:event_id])
    @bar = Bar.new
  end

  def classment
    @event = Event.find(params[:event_id])
    @event_users = Event.find(params[:event_id]).event_users
    @bars = Bar.where(event_id: params[:event_id]).sort { |a, b| b.votes.count <=> a.votes.count }
  end

  private

  def bar_params
    params.require(:bar).permit(:name, :address, :rating, :place_id)
  end

  def first_barycenter
    set_event_users
    @addresses = []
    @eventusers.each do |eventuser|
      @addresses << eventuser.user_address
    end
    @first_barycenter = Geocoder::Calculations.geographic_center(@addresses)
  end

  def second_barycenter
    speed_calculation
    sum_lat = 0
    sum_lng = 0
    sum_speed = 0
    @eventusers.each do |eventuser|
      sum_speed += (1/eventuser.speed)
      sum_lat += eventuser.latitude * (1/eventuser.speed)

      sum_lng += eventuser.longitude * (1/eventuser.speed)

    end
    if sum_speed != 0
      sec_bary_lat = sum_lat / sum_speed.to_f
      sec_bary_lng = sum_lng / sum_speed.to_f
    end
    @event.update(barycenter_lat: sec_bary_lat)
    @event.update(barycenter_lng: sec_bary_lng)
    # Appeler le calcul du barycentre uniquement à la fin (ou quand un nouvel invité arrive), et on supprime donc la liste des bars
  end

  def get_bars_from_google(event)
    # renvoie une réponse de google avec des bars à proximité du baeycentre
    # filtre ces bars selon ton call cad + 4.5 & open quand ça se passe
    url = URI("https://maps.googleapis.com/maps/api/place/nearbysearch/json?keyword=bar&type=bar&location=#{event.barycenter_lat},#{event.barycenter_lng}&rankby=distance&key=#{ENV['GOOGLE_API_KEY']}")

    https = Net::HTTP.new(url.host, url.port)
    https.use_ssl = true

    request = Net::HTTP::Get.new(url)

    response = https.request(request)
    data = JSON.parse(response.read_body)
    # pour chacun de ces bars, tu récupères la place id & tu t'en sers pour un second call si nécessaire
    # Extraire le nom, la note et l'adresse`
    bars = []
    counter = 0
    data["results"]&.each do |bar|
      next if bar.dig("photos").nil?
      photo_url = URI("https://maps.googleapis.com/maps/api/place/photo?maxwidth=400&photoreference=#{bar["photos"]&.first&.dig("photo_reference")}&key=#{ENV['GOOGLE_API_KEY']}")
      next if bar.dig("rating").nil?

      new_bar = Bar.new(
        name: bar["name"],
        rating: bar["rating"],
        address: bar["vicinity"],
        placeid: bar["place_id"],
        photo: photo_url,
        latitude: bar.dig("geometry", "location", "lat"),
        longitude: bar.dig("geometry", "location", "lng"),
        event: event
      )
      bars << new_bar
      counter += 1 unless new_bar.nil?
      break if counter >= 10
    end
    bars = bars.sort_by(&:rating).reverse.first(5)
    @event.bars.destroy_all if bars.length > 1
    bars.each(&:save)
  end

  def speed_calculation
    first_barycenter
    bary_lat = @first_barycenter.first
    bary_lng = @first_barycenter.last
    # @distance = []
    @eventusers.each do |eventuser|
      url = "https://maps.googleapis.com/maps/api/directions/json?origin=#{eventuser.latitude},#{eventuser.longitude}&destination=#{bary_lat},#{bary_lng}&mode=#{eventuser.transport}&arrival_time=#{@event.date.to_i}&key=#{ENV['GOOGLE_API_KEY']}"
      result = JSON.parse(URI.open(url).read)
      if result.dig('available_travel_modes')
        url = "https://maps.googleapis.com/maps/api/directions/json?origin=#{eventuser.latitude},#{eventuser.longitude}&destination=#{bary_lat},#{bary_lng}&mode=walking&arrival_time=#{@event.date.to_i}&key=#{ENV['GOOGLE_API_KEY']}"
        result = JSON.parse(URI.open(url).read)
      end
      distance = result.dig('routes')&.first&.dig('legs')&.first&.dig('distance', 'value')
      duration = result.dig('routes')&.first&.dig('legs')&.first&.dig('duration', 'value')
      eventuser.update(distance: distance, duration: duration)
      if duration.zero?
        eventuser.update(speed: 1)
      else
        eventuser.update(speed: distance.fdiv(duration))
      end
    end
  end

  def set_event_users
    @event = Event.find(params[:event_id])
    @eventusers = @event.event_users
  end
end

# {"geocoded_waypoints"=>
#   [{"geocoder_status"=>"OK", "place_id"=>"ChIJi1DaGFJt5kcRL5RFo8zcuWQ", "types"=>["establishment", "point_of_interest", "school"]},
#    {"geocoder_status"=>"OK", "place_id"=>"ChIJi1DaGFJt5kcRL5RFo8zcuWQ", "types"=>["establishment", "point_of_interest", "school"]}],
#  "routes"=>
#   [{"bounds"=>{"northeast"=>{"lat"=>48.8632846, "lng"=>2.3765937}, "southwest"=>{"lat"=>48.8632846, "lng"=>2.3765937}},
#     "copyrights"=>"Map data ©2023 Google",
#     "legs"=>
#      [{"distance"=>{"text"=>"1 m", "value"=>0},
#        "duration"=>{"text"=>"1 min", "value"=>0},
#        "end_address"=>"68 Ave Parmentier, 75011 Paris, France",
#        "end_location"=>{"lat"=>48.8632846, "lng"=>2.3765937},
#        "start_address"=>"68 Ave Parmentier, 75011 Paris, France",
#        "start_location"=>{"lat"=>48.8632846, "lng"=>2.3765937},
#        "steps"=>
#         [{"distance"=>{"text"=>"1 m", "value"=>0},
#           "duration"=>{"text"=>"1 min", "value"=>0},
#           "end_location"=>{"lat"=>48.8632846, "lng"=>2.3765937},
#           "html_instructions"=>"Head on <b>Rue Lechevin</b>",
#           "polyline"=>{"points"=>"orfiHudoM"},
#           "start_location"=>{"lat"=>48.8632846, "lng"=>2.3765937},
#           "travel_mode"=>"WALKING"}],
#        "traffic_speed_entry"=>[],
#        "via_waypoint"=>[]}],
#     "overview_polyline"=>{"points"=>"orfiHudoM"},
#     "summary"=>"Rue Lechevin",
#     "warnings"=>["Walking directions are in beta. Use caution – This route may be missing sidewalks or pedestrian paths."],
#     "waypoint_order"=>[]}],
#  "status"=>"OK" }

app/views/bars/_bar_classment.html.erb
<div class="card-product justify-content-between m-2 position-relative <%= 'card-bar-voted' if bar.most_voted? %>" style="width: 600px ;border-radius: 5px; padding: 0"
    data-id="<%= bar.id %>"
    data-event-subscription-target="barCard">
  <div class="d-flex align-items-center flex-grow-1" style="height:100%">
  <img src="<%= bar.photo %>" class="bar-img me-2"/>
    <div class="card-product-infos d-flex justify-content-between flex-grow-1">
      <div class="w-100">
        <div class="d-flex justify-content-between">
          <h2><%= bar.name %></h2>
          <i class="fa-solid fa-trophy trophy ms-auto"></i>
        </div>
        <p><%= bar.address %></p>

        <div class="d-flex flex-row align-items-center">
          <div>
          <% if !bar.votes.empty? %>
            <ul class="crop-avatar">
            <% bar.votes.first(4).each do |vote| %>
              <% if vote %>
                <li>
                  <%= cl_image_tag(vote&.user&.photo&.key,class: "miniavatar",
                  :transformation=>[
                  {:gravity=>"face", :height=>50, :crop=>"fill"},
                  {:fetch_format=>"auto"}]) %>
                </li>
              <% end %>
            <% end %>
              <% if bar.votes.count > 4 %>
                <li>
                  <p> +<%= bar.votes.count - 4 %></p>
                </li>
              <% end %>
            </ul>
          <% end %>
          </div>
          <div class="me-2">
            <% if bar.votes.count <= 1 %>
              <p class="ms-1">(<%= bar.votes.count %> vote)</p>
            <% else %>
              <p class="ms-1">(<%= bar.votes.count %> votes)</p>
            <% end %>
          </div>
        </div>
        <p><%= bar.rating %> <i class="fa-solid fa-star"></i></p>
      </div>
    </div>
    </div>
    <%= link_to "Choisir",
    event_choose_bar_path(event, bar: bar),
    data: { toggle_elements_target: "element" },
    class: "btn btn-sm validate-bar-btn "%>
</div>

app/views/bars/_info_window.html.erb
<div class="card-trip" style="width: 100%; border-radius: 5px; padding: 0">
 <%= image_tag bar.photo %>
<div class="card-trip-infos">
  <div>
    <h2><%= bar.name %></h2>
      <p><%= bar.address %></p>
      <p><%= bar.rating %> <i class="fa-solid fa-star"></i></p>
        <%= link_to "vote", event_votes_path(@event, bar: bar), data: { turbo_method: :post }, class: "btn btn-ghost btn-sm", style: "background: #6d5938" %>
  </div>
  </div>
</div>

app/views/bars/_info_window_html.erb
<h2><%= bar.name %></h2>
<p><%= bar.address %></p>

app/views/bars/_marker.html.erb
<%= image_tag "barocentre_biere.png", height: 40, width: 40, alt: "Logo" %>

app/views/bars/classment.html.erb
<div class="justify-content-center" data-controller="event-subscription"
      data-event-subscription-event-id-value="<%= @event.id%>">
    <div class="col-sm-3 col-lg-12 p-4">
      <div class="text-center mt-2">
      <h1><%= @event.name.capitalize %></h1>
          <p class="pb-2">
          <i class="fa-solid fa-crown"></i> <strong><%= @event.user.username %></strong>
        </p>
    </div>
        <p class="border-bottom border-secondary text-left">Participants</p>
    <div class="ranking-wrapper" data-controller="toggle-elements">
      <%# Pour afficher le mot "cloturer le vote, qui va faire apparaitre le bouton choisir" %>
      <% if current_user == @event.user %>
        <div class="d-flex justify-content-center mt-3" style="width:100%">
          <%= link_to "Clôture le vote", event_choose_bar_path(@event), class:"choose-btn btn-ghost"%>
        </div>
      <% end %>
        <div class="row justify-content-center p-3">
          <% @bars.each do |bar| %>
          <%= render "bar_classment", bar: bar, event: @event%>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/bars/index.html.erb
<div class="wraper" style="height: 100%">
  <div class="justify-content-center">
    <div class="col-sm-3 col-lg-12 p-4">
      <div class="text-center  mt-2">
        <h1><%= @event.name.capitalize %></h1>
        <p class="pb-2">
          <i class="fa-solid fa-crown"></i> <strong><%= @event.user.username %></strong>
        </p>
      </div>
       <p class="border-bottom border-secondary">Bars</p>
      <div class="row justify-content-center p-2">
        <% @bars.each do |bar| %>

          <div class="col-sm-12 col-lg-3 card-trip m-3"
               style="width: 400px; border-radius: 5px; padding: 0">
            <%= image_tag bar.photo %>
            <div class="card-trip-infos">
              <div>
                <h2><%= bar.name %></h2>
                <p><%= bar.address %></p>
                <p><%= bar.rating %> <i class="fa-solid fa-star"></i></p>
              </div>
              <%= link_to "VOTE", event_votes_path(@event, bar: bar), data: { turbo_method: :post }, class: "btn btn-ghost btn-sm" %>
            </div>
          </div>

        <% end %>
      </div>
    </div>
    <div class="col-sm-3 col-lg-12 d-flex justify-content-center">
      <%= link_to map_path, class: "btn btn-ghost", style: "border: 1px solid black; border-radius: 20Px; position : fixed; bottom : 30px;" do %>
        CARTE <i class="fa-solid fa-map"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/bars/map.html.erb
<div class="baro-map"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-barmarker-value="<%= @barycenter_marker.to_json%>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
<%= link_to bars_path, class: "btn btn-ghost", style: "border: 1px solid black; color: white; border-radius: 20Px; position : fixed; bottom : 30px; left: 50%; transform: translateX(-50%);" do %>
  LISTE DES BARS</i>
<% end %>