config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  get "dashboard", to: "pages#dashboard" # route du dashboard
  get "events/:id/invite", to: "events#invite", as: :invite # page d'invitation
  get "events/:event_id/bars", to: "bars#index", as: :bars
  post "events/:event_id/bars", to: "bars#create_bars", as: :create_bars
  get "events/:id/barocentre", to: "events#barocentre", as: :barocentre  # page de la map avec barocentre
  get "events/:event_id/bars/map", to: "bars#map", as: :map # page de la map avec les bars
  get "events/:event_id/event_users/map", to: "event_users#map", as: :map_event_users # page de la map avec les event_users
  resources :events, only: [:new, :create, :show] do # route du new, show, create event
    get "/classment", to: "bars#classment", as: :classment # page du classement
    get :choose_bar
    get "/itineraire", to: "events#itineraire", as: :itineraire # page de l'itinéraire
    resources :votes, only: [:create]
    resources :event_users, only: [:new, :create, :index] # route du new, create, index event_user
  end
  resources :event_users, only: [:destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="wavy-rectangle">
  <svg viewBox="0 0 400 150" preserveAspectRatio="xMinYMin meet">
    <path d="M0,100 C150,200 350,0 500,100 L500,00 L0,0 Z" style="stroke: none; fill:#FFD60A;"></path>
  </svg>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_loader.html.erb
<div class="loadingpage">
<div class="wraper" style="background: #003566">
  <div class="container">
      <div class="wall">
          <div class="row row-0">
              <div class="brick brick-0"></div>
              <div class="brick brick-1"></div>
              <div class="brick brick-2"></div>
              <div class="brick brick-3"></div>
              <div class="brick brick-4"></div>
              <div class="brick brick-5"></div>
              <div class="brick brick-6"></div>
              <div class="brick brick-7"></div>
              <div class="brick brick-8"></div>
          </div>
          <div class="row row-1">
              <div class="brick brick-0"></div>
              <div class="brick brick-1"></div>
              <div class="brick brick-2"></div>
              <div class="brick brick-3"></div>
              <div class="brick brick-4"></div>
              <div class="brick brick-5"></div>
              <div class="brick brick-6"></div>
              <div class="brick brick-7"></div>
              <div class="brick brick-8"></div>
          </div>
          <div class="row row-2">
              <div class="brick brick-0"></div>
              <div class="brick brick-1"></div>
              <div class="brick brick-2"></div>
              <div class="brick brick-3"></div>
              <div class="brick brick-4"></div>
              <div class="brick brick-5"></div>
              <div class="brick brick-6"></div>
              <div class="brick brick-7"></div>
              <div class="brick brick-8"></div>
          </div>
          <div class="row row-3">
              <div class="brick brick-0"></div>
              <div class="brick brick-1"></div>
              <div class="brick brick-2"></div>
              <div class="brick brick-3"></div>
              <div class="brick brick-4"></div>
              <div class="brick brick-5"></div>
              <div class="brick brick-6"></div>
              <div class="brick brick-7"></div>
              <div class="brick brick-8"></div>
          </div>
          <div class="row row-4">
              <div class="brick brick-0"></div>
              <div class="brick brick-1"></div>
              <div class="brick brick-2"></div>
              <div class="brick brick-3"></div>
              <div class="brick brick-4"></div>
              <div class="brick brick-5"></div>
              <div class="brick brick-6"></div>
              <div class="brick brick-7"></div>
              <div class="brick brick-8"></div>
          </div>
          <div class="row row-5">
              <div class="brick brick-0"></div>
              <div class="brick brick-1"></div>
              <div class="brick brick-2"></div>
              <div class="brick brick-3"></div>
              <div class="brick brick-4"></div>
              <div class="brick brick-5"></div>
              <div class="brick brick-6"></div>
              <div class="brick brick-7"></div>
              <div class="brick brick-8"></div>
          </div>
          <div class="row row-6">
              <div class="brick brick-0"></div>
              <div class="brick brick-1"></div>
              <div class="brick brick-2"></div>
              <div class="brick brick-3"></div>
              <div class="brick brick-4"></div>
              <div class="brick brick-5"></div>
              <div class="brick brick-6"></div>
              <div class="brick brick-7"></div>
              <div class="brick brick-8"></div>
          </div>
          <div class="row row-7">
              <div class="brick brick-0"></div>
              <div class="brick brick-1"></div>
              <div class="brick brick-2"></div>
              <div class="brick brick-3"></div>
              <div class="brick brick-4"></div>
              <div class="brick brick-5"></div>
              <div class="brick brick-6"></div>
              <div class="brick brick-7"></div>
              <div class="brick brick-8"></div>
          </div>
          <div class="row row-8">
              <div class="brick brick-0"></div>
              <div class="brick brick-1"></div>
              <div class="brick brick-2"></div>
              <div class="brick brick-3"></div>
              <div class="brick brick-4"></div>
              <div class="brick brick-5"></div>
              <div class="brick brick-6"></div>
              <div class="brick brick-7"></div>
              <div class="brick brick-8"></div>
          </div>
      </div>
      <div class="table">
          <div class="barrel">
              <div class="segment segment-0">
                  <div class="crane">
                      <div class="flow"></div>
                      <div class="part part-1"></div>
                      <div class="part part-2"></div>
                      <div class="part part-3"></div>
                      <div class="handle"></div>
                  </div>
              </div>
              <div class="segment segment-1">
                  <div class="circle circle-1"></div>
                  <div class="circle circle-2"></div>
                  <div class="circle circle-3"></div>
                  <div class="circle circle-4"></div>
                  <div class="circle circle-5"></div>
                  <div class="circle circle-6"></div>
              </div>
              <div class="segment segment-2">
                  <div class="circle circle-1"></div>
                  <div class="circle circle-2"></div>
                  <div class="circle circle-3"></div>
                  <div class="circle circle-4"></div>
                  <div class="circle circle-5"></div>
                  <div class="circle circle-6"></div>
              </div>
              <div class="segment segment-3">
                  <div class="circle circle-1"></div>
                  <div class="circle circle-2"></div>
                  <div class="circle circle-3"></div>
                  <div class="circle circle-4"></div>
                  <div class="circle circle-5"></div>
                  <div class="circle circle-6"></div>
              </div>
              <div class="segment segment-4"></div>
              <div class="segment segment-5"></div>
              <div class="segment segment-6"></div>
              <div class="segment segment-7"></div>
              <div class="segment segment-8"></div>
              <div class="segment segment-9"></div>
          </div>
          <div class="mugs">
              <div class="mug full mug-0">
                  <div class="glass">
                      <div class="beer">
                          <div class="foam foam-0"></div>
                          <div class="bubble bubble-0"></div>
                          <div class="foam foam-1"></div>
                          <div class="bubble bubble-1"></div>
                          <div class="foam foam-2"></div>
                          <div class="bubble bubble-2"></div>
                          <div class="foam foam-3"></div>
                          <div class="bubble bubble-3"></div>
                          <div class="foam foam-4"></div>
                          <div class="bubble bubble-4"></div>
                          <div class="foam foam-5"></div>
                          <div class="bubble bubble-5"></div>
                      </div>
                  </div>
              </div>
              <div class="mug full mug-1">
                  <div class="glass">
                      <div class="beer">
                          <div class="foam foam-0"></div>
                          <div class="bubble bubble-0"></div>
                          <div class="foam foam-1"></div>
                          <div class="bubble bubble-1"></div>
                          <div class="foam foam-2"></div>
                          <div class="bubble bubble-2"></div>
                          <div class="foam foam-3"></div>
                          <div class="bubble bubble-3"></div>
                          <div class="foam foam-4"></div>
                          <div class="bubble bubble-4"></div>
                          <div class="foam foam-5"></div>
                          <div class="bubble bubble-5"></div>
                      </div>
                  </div>
              </div>
              <div class="mug filling mug-2">
                  <div class="glass">
                      <div class="beer">
                          <div class="foam foam-0"></div>
                          <div class="bubble bubble-0"></div>
                          <div class="foam foam-1"></div>
                          <div class="bubble bubble-1"></div>
                          <div class="foam foam-2"></div>
                          <div class="bubble bubble-2"></div>
                          <div class="foam foam-3"></div>
                          <div class="bubble bubble-3"></div>
                          <div class="foam foam-4"></div>
                          <div class="bubble bubble-4"></div>
                          <div class="foam foam-5"></div>
                          <div class="bubble bubble-5"></div>
                      </div>
                  </div>
              </div>
              <div class="mug  mug-3">
                  <div class="glass">
                      <div class="beer">
                          <div class="foam foam-0"></div>
                          <div class="bubble bubble-0"></div>
                          <div class="foam foam-1"></div>
                          <div class="bubble bubble-1"></div>
                          <div class="foam foam-2"></div>
                          <div class="bubble bubble-2"></div>
                          <div class="foam foam-3"></div>
                          <div class="bubble bubble-3"></div>
                          <div class="foam foam-4"></div>
                          <div class="bubble bubble-4"></div>
                          <div class="foam foam-5"></div>
                          <div class="bubble bubble-5"></div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-default navbar-light navbar-lewagon navbar-default sticky-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "barocentre_biere.png", class: "navbar-logo"%>
    <% end %>
    <% if action_name == "home" %>
      <p style="color: white; font-family: 'Montserrat'; letter-spacing: 3px; font-size: 20px; position: relative; top: 9px;">
        BAROCENTRE
      </p>
    <% end %>
    <button class="navbar-toggler" style="border: 0px" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item border-bottom p-2">
           <% if current_user.photo.attached? %>
             <%= cl_image_tag current_user.photo.key, class:"avatar" %>
          <% else %>
            <%= image_tag "https://as1.ftcdn.net/v2/jpg/03/53/11/00/1000_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <span class="ms-2" style="color: white"><%= current_user.username %></span>

          </li>
          <li class="nav-item p-2">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link", style: "color: white" %>
          </li>
          <li class="nav-item p-2">
            <%= link_to "Créer un événement", new_event_path, class: "nav-link", style: "color: white" %>
          </li>
          <li class="nav-item p-2">
            <%= link_to "Déconnexion", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link", style: "color: white" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link", style: "color: white" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>