config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  get "dashboard", to: "pages#dashboard" # route du dashboard
  get "events/:id/invite", to: "events#invite", as: :invite # page d'invitation
  get "events/:event_id/bars", to: "bars#index", as: :bars
  post "events/:event_id/bars", to: "bars#create_bars", as: :create_bars
  get "events/:id/barocentre", to: "events#barocentre", as: :barocentre  # page de la map avec barocentre
  get "events/:event_id/bars/map", to: "bars#map", as: :map # page de la map avec les bars
  get "events/:event_id/event_users/map", to: "event_users#map", as: :map_event_users # page de la map avec les event_users
  resources :events, only: [:new, :create, :show] do # route du new, show, create event
    get "/classment", to: "bars#classment", as: :classment # page du classement
    get :choose_bar
    get "/itineraire", to: "events#itineraire", as: :itineraire # page de l'itinéraire
    resources :votes, only: [:create]
    resources :event_users, only: [:new, :create, :index] # route du new, create, index event_user
  end
  resources :event_users, only: [:destroy]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :event_users, dependent: :destroy
  has_many :bars
  belongs_to :selected_bar, class_name: :Bar, foreign_key: :bar_id, optional: true
  validates :name, presence: true
  validates :date, presence: true

  enum status: {
    created: 0,
    open: 1,
    vote: 2,
    closed: 3
  }

  scope :ongoing, -> { where(status: [:open, :vote]) }
  scope :past, -> { where('date < :today', today: DateTime.now) }
  scope :future, -> { where('date > :today', today: DateTime.now) }
  scope :for_user, -> (user) {
    joins("LEFT JOIN event_users ON event_users.event_id = events.id")
    .where("events.user_id = ? OR event_users.user_id = ?", user.id, user.id)
    .distinct
  }

  def most_voted_bars
    bars.group_by do |bar|
      bar.votes.count
    end.to_a.sort_by(&:first).last.last
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :invite ]


  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save!
      redirect_to event_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def invite
    @event = Event.find(params[:id])
  end

  def choose_bar
    # nest la methode choose bar dans events afin de récupérer l'id de l'event
    # quand on clique sur choisir, aller sur la route "choose", et passer en argument dans l'url l'ID du bar
    # stocker l'id du bar dans 'selected_bar_id' de l'event`
    # @bar = Bar.find(params[:bar])
    # @event = Event.find(params[:event_id])
    # @event.selected_bar = @bar
    # @event.save
    # @event.closed!
    # # sauvegarder l'event
    # # et redirifer sur la page itinéraire
    # redirect_to event_itineraire_path(@event)
    @event = Event.find(params[:event_id])
    @bar = @event.most_voted_bars.sort_by(&:rating).last
    @event.selected_bar = @bar
    @event.save
    @event.closed!
    redirect_to event_itineraire_path(@event)

  end

  def itineraire
    @event = Event.find(params[:event_id])
    @bar = @event.selected_bar
    @eventusers = @event.event_users
    @markers = @eventusers.geocoded.map do |eventuser|
      {
        lat: eventuser.latitude,
        lng: eventuser.longitude,
        marker_html: render_to_string(partial: "event_users/marker", locals: {event_user: eventuser} )
      }
    end
    @finalbarmarker = [{
      lat: @bar.latitude,
      lng: @bar.longitude,
      marker_html: render_to_string(partial: "events/marker")
    }]
    
    redirect_to :back, notice: "Il y a eu une erreur, veuillez recommencer" if @bar.nil?
    @event_user = EventUser.where(user: current_user, event: @event).first
  end

  def show
    @event = Event.find(params[:id])
  end

  def share
    @event = Event.find(params[:id])
  end

  def barocentre
    @event = Event.find(params[:id])
    @eventusers = @event.event_users
    @markers = @eventusers.geocoded.map do |eventuser|
      {
        lat: eventuser.latitude,
        lng: eventuser.longitude,
        user_name: eventuser.user.email,
        info_window_html: render_to_string(partial: "event_users/info_window", locals: {event_user: eventuser} ),
        marker_html: render_to_string(partial: "event_users/marker", locals: {event_user: eventuser} )
      }
    end
    @barycenter_marker = [{
      lat: @event.barycenter_lat,
      lng: @event.barycenter_lng,
      marker_html: render_to_string(partial: "event_users/marker", locals: {event_user: @event}),
    }]
  end

  private

  def event_params
    params.require(:event).permit(:name, :date)
  end

end

app/views/events/_info_window.html.erb
<h4><%= event_user.user_address %></h4>
<p><%= event_user.user.email %></p>
<p><%= translate(event_user.transport) %></p>

app/views/events/_marker.html.erb
<%= image_tag "barocentre_biere.png", height: 40, width: 40, alt: "Logo" %>

app/views/events/_user_marker.html.erb
<% if event_user.user.photo.attached? %>
  <%= cl_image_tag event_user.user.photo.key, :width=>50, :height=>50, :radius=>"max", :crop=>"fill", class: "rounded-circle avatar-bordered" %>
<% else %>
  <%= image_tag "https://as1.ftcdn.net/v2/jpg/03/53/11/00/1000_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg", class: "rounded-circle", style: " width: 50px"%>
<% end %>

app/views/events/barocentre.html.erb
<div class="wraper">
  <div class="baro-map"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-barmarker-value="<%= @barycenter_marker.to_json%>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

  <%= link_to "Voir les bars", bars_path(@event), class: "btn btn-ghost", style: "position: fixed; bottom: 30px; left: 50%; transform: translateX(-50%);" %>
</div>

app/views/events/invite.html.erb
<div class="container hauteur flex-column square-box d-flex justify-content-center align-items-center mt-5">
  <% if user_signed_in?%>
    <% if current_user.photo.attached? %>
      <%= cl_image_tag current_user.photo.key, :width=>250, :height=>250, :radius=>"max", :crop=>"fill" %>
    <% else %>
      <%= image_tag "https://as1.ftcdn.net/v2/jpg/03/53/11/00/1000_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg", class: "rounded-circle", style: " width: 250px"%>
    <% end %>
    <br><br>
    <h2 class=>tu as reçu une invitation de</h2>
    <h2><strong><%= @event.user.username %></strong></h2>
    <br>
    <h3 class="text-center lw"> Rejoins le groupe "<%= @event.name.capitalize %>"</h3>
    <h6>À la date de : <%= @event.date %></h6>
    <br>

    <div class="d-flex">
      <div class="m-1"><%= link_to "Se localiser", new_event_event_user_path(@event), class: "button2" %></div>
    </div>


  <% else %>
      <%= image_tag "https://as1.ftcdn.net/v2/jpg/03/53/11/00/1000_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg", class: "rounded-circle", style: " width: 250px"%>
    <br><br>
    <h2 class=>tu as reçu une invitation de</h2>
    <h2><strong><%= @event.user.email %></strong></h2>
    <br>
    <h3 class="text-center lw"> Rejoins le groupe "<%= @event.name.capitalize %>"</h3>
    <h6>À la date de : <%= @event.date %></h6>
    <br>


    <div class="d-flex">
      <div class ="m-1"><%= link_to "Inscription", new_user_registration_path, class: "button2" %></div>
      <div class="m-1"><%= link_to "Connexion", new_user_session_path, class: "button2" %></div>
    </div>
  <% end %>
</div>

app/views/events/itineraire.html.erb
<div class="baro-map"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-finalbarmarker-value="<%= @finalbarmarker.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
<div class="card-product" style="width: 300px; border-radius: 5px; padding: 0; position : fixed; bottom : 50px; right: 35px">
  <%= image_tag @bar.photo, class: "bar-img" %>
  <div class="card-product-infos">
    <div>
      <h2><%= @bar.name %></h2>
      <p><%= @bar.address %></p>
      <p><%= @bar.rating %> <i class="fa-solid fa-star"></i></p>
    </div>
  </div>
</div>
      <%= link_to 'Itinéraire', "https://www.google.com/maps/dir/?api=1&origin=#{CGI.escape(@event_user.user_address)}&destination=barocentre&destination_place_id=#{@bar.placeid}&travelmode=#{@event_user.transport}", class: 'btn btn-flat', target: '_blank', style: "position : fixed; bottom : 30px; right: 20px; border-radius: 20px" %>

app/views/events/new.html.erb
<div class="d-flex justify-content-center mt-3 p-3" style="background: white; width: 350px; height: 750px; margin: 0 auto">

      <%= simple_form_for @event, html: {
                      data: {
                        controller: 'flatpickr'
                      }
                    }  do |f| %>
        <div class="form-inputs">
          <div class="d-flex justify-content-center mb-4">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, :width=>200, :height=>200, :radius=>"max", :crop=>"fill", class: "rounded-circle", style: "  box-shadow: 0 70px 63px -60px #000000" %>
            <% else %>
              <%= image_tag "https://as1.ftcdn.net/v2/jpg/03/53/11/00/1000_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg", class: "rounded-circle", style: " width: 250px"%>
            <% end %>

          </div>
          <%= f.input :date,
                      label: false,
                      as: :string,
                      input_html: {
                        class: "d-none",
                        data: {
                          flatpickr_target: 'dateInput',
                        }
                      } %>
          <%= f.input :event_status,
                      input_html: { value: "0" },
                      as: :hidden %>
          <div class="mt-3">
            <%= f.input :name,
                label: false,
                placeholder: "Nom de l'événement" %>
          </div>
          <div class="form-actions">
            <div class="d-flex justify-content-between">
              <%= link_to root_path, class:"btn btn-secondary mt-3", style: "background: #0E0000; border: 0px" do %>
                <i class="fa-solid fa-arrow-left"></i>
              <% end %>
              <%= f.button :submit, "Je crée mon événement", class: "btn btn-ghost mt-3", style: "border: 0px" %>
            </div>
        </div>
      <% end %>
        </div>


</div>

app/views/events/show.html.erb
<div class="custom-container container">
  <% if current_user == @event.user %>
    <div class="d-flex justify-content-end pt-2">
      <% if current_user.photo.attached? %>
        <%= cl_image_tag current_user.photo.key, width: 70, height: 70, :radius=>"max", :crop=>"fill", class: "rounded-circle" %>
      <% else %>
        <%= image_tag "https://as1.ftcdn.net/v2/jpg/03/53/11/00/1000_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg", class: "rounded-circle", style: "width: 70px"%>
      <% end %>
    </div>
    <div class="flex-column square-box d-flex justify-content-center align-items-center">
      <h2 class="align-items-center text-center my-4">
        <span class="fs-1" style="color: #001D3D; font-size: 30px !important">
          <%= @event.name.capitalize %>
        </span>
      </h2>


    <div class="badge anim">
      <div class="beer-animation-wrapper">
        <div class="beer">
          <div class="foam"></div>
        </div>
      </div>
    </div>


      <div class ="mt-5">
        <span class="share-btn" data-controller="share"
            data-action="click->share#share"
            data-share-title-value="<%= @event.name %>"
            data-share-url-value="<%= new_event_event_user_url(@event) %>">
          Inviter les copains <i class="fa-solid fa-share-from-square"></i>
        </span>
        <br>
        <br>
      </div>
      <% unless current_user && current_user.participates_to_event?(@event) %>
        <div class ="mt-5">
          <%= link_to root_path, class: "btn-secondary m-1" do %>
            <i class="fa-solid fa-arrow-left"></i>
          <% end%>
          <%= link_to "S'inscrire", new_event_event_user_path(@event), class: "btn-ghost m-1" %>

        </div>
      <% else %>
        <div class ="m-1">
          <%= link_to "Continuer", event_event_users_path(@event), class: "btn-ghost" %>
          <%= link_to "back", root_path, class: "btn-secondary" %>
        </div>
      <% end %>
    </div>



  <% else %>
    <div class="container hauteur flex-column square-box d-flex justify-content-center align-items-center">
      <h1>ACCESS DENY</h1>
    </div>
  <% end %>
</div>

<%= render 'shared/footer' %>